version: '3.8'

services:
  app:
    build: .
    command: node dist/main.js
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '3.0'     
          